window.EUROLEAGUE_TEAMS_2026_27 = [
  {
    id: "olympiacos",
    name: "Olympiacos Piraeus",
    shortName: "Olympiacos",
    country: "Greece",
    logo: "assets/logos/olympiacos.png",
  },
  {
    id: "real-madrid",
    name: "Real Madrid",
    shortName: "Real Madrid",
    country: "Spain",
    logo: "assets/logos/real-madrid.png",
  },
  {
    id: "fenerbahce",
    name: "Fenerbahce Tarfin Istanbul",
    shortName: "Fenerbahce",
    country: "Turkey",
    logo: "assets/logos/fenerbahce.png",
  },
  {
    id: "panathinaikos",
    name: "Panathinaikos AKTOR Athens",
    shortName: "Panathinaikos",
    country: "Greece",
    logo: "assets/logos/panathinaikos.png",
  },
  {
    id: "barcelona",
    name: "FC Barcelona",
    shortName: "Barcelona",
    country: "Spain",
    logo: "assets/logos/barcelona.png",
  },
  {
    id: "anadolu-efes",
    name: "Anadolu Efes Istanbul",
    shortName: "Anadolu Efes",
    country: "Turkey",
    logo: "assets/logos/anadolu-efes.png",
  },
  {
    id: "partizan",
    name: "Partizan Mozzart Bet Belgrade",
    shortName: "Partizan",
    country: "Serbia",
    logo: "assets/logos/partizan.png",
  },
  {
    id: "maccabi-tel-aviv",
    name: "Maccabi Rapyd Tel Aviv",
    shortName: "Maccabi Tel Aviv",
    country: "Israel",
    logo: "assets/logos/maccabi-tel-aviv.png",
  },
  {
    id: "bayern-munich",
    name: "FC Bayern Munich",
    shortName: "Bayern Munich",
    country: "Germany",
    logo: "assets/logos/bayern-munich.png",
  },
  {
    id: "zalgiris",
    name: "Zalgiris Kaunas",
    shortName: "Zalgiris",
    country: "Lithuania",
    logo: "assets/logos/zalgiris.png",
  },
  {
    id: "crvena-zvezda",
    name: "Crvena Zvezda Meridianbet Belgrade",
    shortName: "Crvena Zvezda",
    country: "Serbia",
    logo: "assets/logos/crvena-zvezda.png",
  },
  {
    id: "virtus-bologna",
    name: "Virtus Bologna",
    shortName: "Virtus Bologna",
    country: "Italy",
    logo: "assets/logos/virtus-bologna.png",
  },
  {
    id: "olimpia-milan",
    name: "Armani Olimpia Milan",
    shortName: "Olimpia Milan",
    country: "Italy",
    logo: "assets/logos/olimpia-milan.png",
  },
  {
    id: "baskonia",
    name: "Kosner Baskonia Vitoria-Gasteiz",
    shortName: "Baskonia",
    country: "Spain",
    logo: "assets/logos/baskonia.png",
  },
  {
    id: "asvel",
    name: "LDLC ASVEL Villeurbanne",
    shortName: "ASVEL",
    country: "France",
    logo: "assets/logos/asvel.png",
  },
  {
    id: "paris-basketball",
    name: "Paris Basketball",
    shortName: "Paris",
    country: "France",
    logo: "assets/logos/paris-basketball.png",
  },
  {
    id: "valencia-basket",
    name: "Valencia Basket",
    shortName: "Valencia",
    country: "Spain",
    logo: "assets/logos/valencia-basket.png",
  },
  {
    id: "dubai-basketball",
    name: "Dubai Basketball",
    shortName: "Dubai",
    country: "United Arab Emirates",
    logo: "assets/logos/dubai-basketball.png",
  },
  {
    id: "hapoel-tel-aviv",
    name: "Hapoel IBI Tel Aviv",
    shortName: "Hapoel Tel Aviv",
    country: "Israel",
    logo: "assets/logos/hapoel-tel-aviv.png",
  },
  {
    id: "besiktas",
    name: "Besiktas Istanbul",
    shortName: "Besiktas",
    country: "Turkey",
    logo: "assets/logos/besiktas.png",
  },
];
